NAME =

OUTPUT_DIR = build

SRC_DIR = src

OUT_DIRS := $(OUTPUT_DIR)/$(SRC_DIR)

SRC = $(SRC_DIR)/ClapTrap.cpp	\
	  $(SRC_DIR)/ScavTrap.cpp	\
	  $(SRC_DIR)/main.cpp

INCLUDES = includes

include src/Makefile
