NAME = war

OUTPUT_DIR = build

SRC_DIR = src

OUT_DIRS := $(OUTPUT_DIR)/$(SRC_DIR)

SRC = $(SRC_DIR)/main.cpp		\
		$(SRC_DIR)/HumanA.cpp	\
		$(SRC_DIR)/HumanB.cpp	\
		$(SRC_DIR)/Weapon.cpp

INCLUDES = includes

include src/Makefile
