NAME = animals

OUTPUT_DIR = build

SRC_DIR = src

OUT_DIRS := $(OUTPUT_DIR)/$(SRC_DIR)

SRC = $(SRC_DIR)/Animal.cpp	\
	  $(SRC_DIR)/Dog.cpp	\
	  $(SRC_DIR)/Cat.cpp	\
	  $(SRC_DIR)/main.cpp

INCLUDES = includes

include src/Makefile
