NAME = phonebook

OUTPUT_DIR = build

SRC_DIR = src

OUT_DIRS := $(OUTPUT_DIR)/$(SRC_DIR)

SRC = $(SRC_DIR)/main.cpp		\
	  $(SRC_DIR)/phonebook.cpp	\
	  $(SRC_DIR)/contact.cpp

INCLUDES = includes

include src/Makefile
