NAME = zombie

OUTPUT_DIR = build

SRC_DIR = src

OUT_DIRS := $(OUTPUT_DIR)/$(SRC_DIR)

SRC = $(SRC_DIR)/main.cpp		\
	  $(SRC_DIR)/Zombie.cpp		\
	  $(SRC_DIR)/newZombie.cpp	\
	  $(SRC_DIR)/randomChump.cpp

INCLUDES = includes

include src/Makefile
